export enum FmIncomingWindowMessage {
  FORTMATIC_HANDLE_RESPONSE = 'FORTMATIC_HANDLE_RESPONSE',
  FORTMATIC_OVERLAY_READY = 'FORTMATIC_OVERLAY_READY',
  FORTMATIC_SHOW_OVERLAY = 'FORTMATIC_SHOW_OVERLAY',
  FORTMATIC_HIDE_OVERLAY = 'FORTMATIC_HIDE_OVERLAY',
  FORTMATIC_USER_DENIED = 'FORTMATIC_USER_DENIED',
  FORTMATIC_USER_LOGOUT = 'FORTMATIC_USER_LOGOUT',
}

export enum FmOutgoingWindowMessage {
  FORTMATIC_HANDLE_BATCH_REQUEST = 'FORTMATIC_HANDLE_BATCH_REQUEST',
  FORTMATIC_HANDLE_REQUEST = 'FORTMATIC_HANDLE_REQUEST',
  FORTMATIC_HANDLE_FORTMATIC_REQUEST = 'FORTMATIC_HANDLE_FORTMATIC_REQUEST',
}
